// import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faEnvelope,
  faAngleDown,
  faBars,
  faBell,
  faBullhorn,
  faCaretDown,
  faClock,
  faCommentDots,
  faHome,
  faSearch,
  faSignOutAlt,
  faTrashAlt,
  faUsers,
  faCog,
  faHeart,
  faVideo,
  faImage,
  faPlus,
  faCaretRight,
  faCaretUp,
  faSmile,
  faTimes,
  faGlobe,
  faThumbsUp,
  faShare,
  faPlay,
  faHandsWash,
  faArrowDown,
  faAngleUp,
  faDonate,
  faGraduationCap,
  faBookReader,
  faHandHoldingHeart,
  faChartBar,
  faHandsHelping,
  faPhone,
  faLocationArrow,
  faGenderless,
  faSchool,
  faAddressBook,
  faEdit,
  faClosedCaptioning,
  faMapMarkerAlt,
  faBirthdayCake,
  faRunning,
  faDollarSign,
  faCamera,
  faAngleRight,
  faAngleLeft,
  faPaperPlane,
  faEllipsis,
} from '@fortawesome/free-solid-svg-icons';
import { faFacebook, faGithub, faInstagram, faLinkedinIn, faTwitter, faWhatsapp } from '@fortawesome/free-brands-svg-icons';

// library.add(faUser, faEnvelope, faGithub, faTwitter);

export const FaIcons = {
  faEllipsis: faEllipsis,
  User: faUser,
  Facebook: faFacebook,
  Envelope: faEnvelope,
  Github: faGithub,
  Twitter: faTwitter,
  Bars: faBars,
  Gear: faCog,
  Search: faSearch,
  PeopleGroup: faUsers,
  CommentDots: faCommentDots,
  CaretDown: faCaretDown,
  Bell: faBell,
  Home: faHome,
  Anuncios: faBullhorn,
  AngleDown: faAngleDown,
  AngleUp: faAngleUp,
  AngleRight: faAngleRight,
  AngleLeft: faAngleLeft,
  Logout: faSignOutAlt,
  Clock: faClock,
  Trash: faTrashAlt,
  Heart: faHeart,
  Image: faImage,
  Video: faVideo,
  Plus: faPlus,
  World: faGlobe,
  CaretUp: faCaretUp,
  Caret: faCaretRight,
  Times: faTimes,
  Smile: faSmile,
  Like: faThumbsUp,
  Share: faShare,
  Play: faPlay,
  HandsClapping: faHandsWash,
  ClockRotateLeft: faClock,
  ArrowDown: faArrowDown,
  Donate: faHandHoldingHeart,
  faGraduationCap: faGraduationCap, 
  faBookReader: faBookReader,
  Chart: faChartBar,
  HandsHelping: faHandsHelping,
  DonateOrg: faDonate,
  Phone: faPhone,
  Location: faLocationArrow,
  Gender: faGenderless,
  School: faSchool,
  Address: faMapMarkerAlt,
  Edit: faEdit,
  Birthday: faBirthdayCake,
  Work: faRunning,
  Dollar: faDollarSign,
  Camera: faCamera,
  Send: faPaperPlane,
  Instagram: faInstagram,
  Whatsapp: faWhatsapp,
  Linkedin: faLinkedinIn
  // adicione aqui as variáveis para outros ícones que você queira usar
};
